version: "2"

services:
  sut:
    build: .
    image: pingidentity/pingdatagovernance:${TAG}
    environment:
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=getting-started/pingdatagovernance
    command: start-server /opt/wait-for localhost:443 -t 300 -- /opt/liveness.sh

    